#!/bin/sh

cd $(dirname $0)
docker run -it --rm -v "$PWD":/usr/src/app -v site:/usr/src/app/_site -p "4000:4000" starefossen/github-pages
#docker run -i -t -v "$PWD:/home/jenkins" -p 4000:4000 praqma/gh-pages jekyll serve --watch --host=0.0.0.0