#!/usr/bin/env bash

PROJECT=$1
rm -rf test
mkdir test
cd test
opp_env list
opp_env info $PROJECT
opp_env download $PROJECT
opp_env clean $PROJECT
opp_env build $PROJECT
opp_env shell $PROJECT
opp_env run -c "cd $PROJECT/samples/aloha && ./aloha -c PureAloha1" $PROJECT
