#!/bin/sh

DOCKER_BUILDKIT=1 podman build -t ghcr.io/omnetpp/opp_env:latest -t ghcr.io/omnetpp/opp_env:$(date +%y%m%d) .

podman run --user opp_env --replace --name opp_env_wsl ghcr.io/omnetpp/opp_env:latest
podman export opp_env_wsl | gzip --best > opp_env.wsl
podman rm opp_env_wsl
